### PR TITLE
chore: Support numpy v2

### PR DESCRIPTION
**Pull request by phi-friday**
https://github.com/bayesian-optimization/BayesianOptimization/issues/490#issue-2394383006

### CODE REVIEW

**Comment by phi-friday** [comment]
passed all tests in local. (arm mac)
```shell
❯ poetry run pip freeze
alabaster==0.7.16
anyio==4.4.0
appnope==0.1.4
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
arrow==1.3.0
asttokens==2.4.1
async-lru==2.0.4
attrs==23.2.0
Babel==2.15.0
-e git+ssh://git@github.com/phi-friday/BayesianOptimization.git@21cd18cd95996db9745093d6a3de40d1b531ffa5#egg=bayesian_optimization
beautifulsoup4==4.12.3
bleach==6.1.0
certifi==2024.7.4
cffi==1.16.0
charset-normalizer==3.3.2
colorama==0.4.6
comm==0.2.2
contourpy==1.2.1
coverage==7.5.4
cycler==0.12.1
debugpy==1.8.2
decorator==5.1.1
defusedxml==0.7.1
docutils==0.20.1
executing==2.0.1
fastjsonschema==2.20.0
fonttools==4.53.1
fqdn==1.5.1
h11==0.14.0
httpcore==1.0.5
httpx==0.27.0
idna==3.7
imagesize==1.4.1
iniconfig==2.0.0
ipykernel==6.29.5
ipython==8.18.1
ipywidgets==8.1.3
isoduration==20.11.0
jedi==0.19.1
Jinja2==3.1.4
joblib==1.4.2
json5==0.9.25
jsonpointer==3.0.0
jsonschema==4.22.0
jsonschema-specifications==2023.12.1
jupyter==1.0.0
jupyter-console==6.6.3
jupyter-events==0.10.0
jupyter-lsp==2.2.5
jupyter_client==8.6.2
jupyter_core==5.7.2
jupyter_server==2.14.1
jupyter_server_terminals==0.5.3
jupyterlab==4.2.3
jupyterlab_pygments==0.3.0
jupyterlab_server==2.27.2
jupyterlab_widgets==3.0.11
kiwisolver==1.4.5
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib==3.9.1
matplotlib-inline==0.1.7
mdit-py-plugins==0.4.1
mdurl==0.1.2
mistune==3.0.2
myst-parser==3.0.1
nbclient==0.10.0
nbconvert==7.16.4
nbformat==5.10.4
nbsphinx==0.9.4
nest-asyncio==1.6.0
notebook==7.2.1
notebook_shim==0.2.4
numpy==2.0.0
overrides==7.7.0
packaging==24.1
pandocfilters==1.5.1
parso==0.8.4
pexpect==4.9.0
pillow==10.4.0
platformdirs==4.2.2
pluggy==1.5.0
prometheus_client==0.20.0
prompt_toolkit==3.0.47
psutil==6.0.0
ptyprocess==0.7.0
pure-eval==0.2.2
pycparser==2.22
pydocstyle==6.3.0
Pygments==2.18.0
pyparsing==3.1.2
pytest==8.2.2
pytest-cov==4.1.0
python-dateutil==2.9.0.post0
python-json-logger==2.0.7
PyYAML==6.0.1
pyzmq==26.0.3
qtconsole==5.5.2
QtPy==2.4.1
referencing==0.35.1
requests==2.32.3
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rpds-py==0.18.1
scikit-learn==1.5.1
scipy==1.13.1
Send2Trash==1.8.3
setuptools==70.2.0
six==1.16.0
sniffio==1.3.1
snowballstemmer==2.2.0
soupsieve==2.5
Sphinx==7.3.7
sphinx-rtd-theme==2.0.0
sphinxcontrib-applehelp==1.0.8
sphinxcontrib-devhelp==1.0.6
sphinxcontrib-htmlhelp==2.0.5
sphinxcontrib-jquery==4.1
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.7
sphinxcontrib-serializinghtml==1.1.10
stack-data==0.6.3
terminado==0.18.1
threadpoolctl==3.5.0
tinycss2==1.3.0
tornado==6.4.1
traitlets==5.14.3
types-python-dateutil==2.9.0.20240316
uri-template==1.3.0
urllib3==2.2.2
wcwidth==0.2.13
webcolors==24.6.0
webencodings==0.5.1
websocket-client==1.8.0
widgetsnbextension==4.0.11
```

**Comment by phi-friday** [comment]
add new test action variable `numpy-version`
passed all tests in github.

https://github.com/phi-friday/BayesianOptimization/actions/runs/9838712868

스크린샷 2024-07-08 오후 8 33 12

**Comment by till-m** [comment]
Generally looks good to me, could you maybe adjust the name of the job to make clear what the numbers refer to? See e.g. [here](https://github.com/nalepae/pandarallel/blob/master/.github/workflows/run_tests.yml) on how to do that.

**Comment by phi-friday** [comment]
> Generally looks good to me, could you maybe adjust the name of the job to make clear what the numbers refer to? See e.g. [here](https://github.com/nalepae/pandarallel/blob/master/.github/workflows/run_tests.yml) on how to do that.

like this?
```yaml
jobs:
  build:
    name: Python ${{ matrix.python-version }} - numpy ${{ matrix.numpy-version }}
```

**Comment by phi-friday** [comment]
> > Generally looks good to me, could you maybe adjust the name of the job to make clear what the numbers refer to? See e.g. [here](https://github.com/nalepae/pandarallel/blob/master/.github/workflows/run_tests.yml) on how to do that.
> 
> like this?
> 
> ```yaml
> jobs:
>   build:
>     name: Python ${{ matrix.python-version }} - numpy ${{ matrix.numpy-version }}
> ```

example: https://github.com/phi-friday/BayesianOptimization/actions/runs/9839301603

**Review by till-m — APPROVED** [review]

**Review by brendan-whelan-seetreat — APPROVED** [review]

**Comment by till-m** [comment]
thanks for your contribution!

**Pull request merged**
