### PR TITLE
Prepare for release

### PR DESCRIPTION
**Pull request by till-m**

### CODE REVIEW

**Comment by till-m** [comment]
@bwheelz36 is this a [minor or patch release](https://semver.org/)? Maybe it should be `1.6.0` 🤔

**Comment by bwheelz36** [comment]
Hmm. Probably a patch? That's a "backward compatible bug fix"

**Comment by bwheelz36** [comment]
Actually I'm just referring to the numpy change. Is anything else included?

**Comment by till-m** [comment]
A few other things, yeah, see comparison to master [here](https://github.com/bayesian-optimization/BayesianOptimization/compare/v1.5.0...master).

**Comment by till-m** [comment]
I think it's fine to call these things bugfixes, so I'll ship it under this.

**Pull request merged**
