### PR TITLE
Parameter Typing

### LINKED ISSUE #93: Support different data types for optimization parameters
It would be nice to support different data types---e.g. `int`, `float`, `bool`, and maybe a categorical string---for the parameters over which we optimize. I am not sure what the syntax would look like, except for maybe a list of datatypes passed in that corresponds to the parameter bounds.

All three of these types could be handled the same way, with `int` being drawn uniformly from the integer interval specified, `bool` being drawn uniformly from `{0, 1}`, and categorical strings being mapped to a drawing from integer values `[0, 1, ..., n_categories-1]` or one-hot encoded as @PedroCardoso suggested below.

See [[E. C. Garrido-Merchan and D. Hernandez-Lobato, 2017]][0] for one approach.

[0]: https://arxiv.org/pdf/1706.03673.pdf

### PR DESCRIPTION
**Pull request by till-m**
fixes #93 #191 #308 #376 by adding support for different parameter types: float (the default), int, and categorical. This should cover the majority of the usecases.

(there is still some stuff left to do before this can be merged but I would like to know whether merging this is something we want to consider in the first place before doing that work).

Adds experimental support for parameter typing. 

This adds a pretty serious layer of complexity (one could even call it spaghettification in some cases) to the code base.

Checklist:
- [x] Make sure the original functionality works as before
- [x] Add basic support for parameters
- [ ] Add more tests
- [ ] Check parameters and constraints
- [ ] Check parameters and Domain Reduction
- [ ] ...probably more?
- [ ] Figure out how to retain the serializability

I'm primarily looking for feedback here: Is this worth adding? Is this worth the additional technical debt? Is there a better way to handle the problem of parameter types?

### CODE REVIEW

**Comment by till-m** [comment]
Demo: [notebook](https://github.com/bayesian-optimization/BayesianOptimization/blob/ac7f253bd2d39b57a54f916174c954a14503e5ed/examples/parameter_types.ipynb).

**Comment by till-m** [comment]
Based on [this paper](https://arxiv.org/abs/1805.03463).

**Comment by bwheelz36** [comment]
the implementation in the notebook appears really elegant. I think a lot of people would be happy with this feature. It does look like a pretty large amount of work though!  But I would say yes this would be a desired feature.

**Comment by PassengerC07** [comment]
Hi,

I think for hyperparameter tuning, this feature is a must-have, especially if bound transformer is used. This is really nice work! This is going to improve the algorithm's efficiency for tuning the parameters which are in a lot of cases not float.

**Comment by till-m** [comment]
I will close this for now, since I think the added technical debt is not really worth it. If I can think of a better way of handling the parameter problem, I will make a new PR.

**Pull request closed without merging**
