### PR TITLE
updated documentation

### PR DESCRIPTION
**Pull request by bpmeek**
updated documentation to change `BayesianOptimization` to `bayesian_optimization`

### CODE REVIEW

**Comment by till-m** [comment]
Hi @bpmeek,

I think the documentation is correct as-is. Why do you think this change is necessary?

**Comment by bpmeek** [comment]
When I was implementing it yesterday I was getting import errors until I changed it. I can try to dig into it more later today.

**Comment by bpmeek** [comment]
@till-m you're right, there must have been an issue with my IDE yesterday, it's working correctly today.

**Comment by till-m** [comment]
@bpmeek in any case, your willingness to make contributions is very appreciated :)

**Pull request closed without merging**
