### PR TITLE
PR 1/2: Add versioned docs

### LINKED ISSUE #504: Docs: Deploy Multiple Versions
**Is your feature request related to a problem? Please describe.**
Currently, we are hosting one version of the docs, specifically a version that is synced with `master`. However, users might be using older versions of the package. Even if using the most recently released version, this can differ from `master` (e.g. see #500).

**Describe the solution you'd like**
Sphinx does, in principle, support a collapsible nav item for multiple versions, see e.g. in [this example](https://docs.conan.io/2/) (bottom left). Ideally, this would store the documentation of each `tag`ged version and `master`, defaulting to the highest-versioned release.

**References or alternative approaches**
Relevant links:
- [Blogpost](https://www.codingwiththomas.com/blog/my-sphinx-best-practice-for-a-multiversion-documentation-in-different-languages) about this topic
- [Stackoverflow answer](https://stackoverflow.com/a/73826022) discussing an implementation
- [GH Action: Publish to subdirectory](https://github.com/peaceiris/actions-gh-pages?tab=readme-ov-file#%EF%B8%8F-deploy-to-subdirectory-destination_dir)

Examples:
- [Conan](https://docs.conan.io/2/)
- [rinohtype](http://www.mos6581.org/rinohtype/master/)

**Additional context**
Does not need to be retroactive -- i.e. once we have it deployed we can simply add versions going forward.

**Are you able and willing to implement this feature yourself and open a pull request?**
- [ ] Yes, I can provide this feature.

Unfortunately, I don't think I am capable of adding this myself.

### PR DESCRIPTION
**Pull request by till-m**
Fix #504 

Demo: https://till-m.github.io/BayesianOptimization/

This adds a version dropdown to our docs page. In the future, any new release will be added to this version dropdown automatically. Similarly, it will keep an updated version of the `master` docs.

I had to switch to `sphinx-immaterial` to get this to work. I’ve also cleaned up the docs a bit and made everything look nicer (imo).

I've also trimmed the README significantly.

## How does it work?
There’s a workflow that runs on push (master), pull request and release. This workflow does a number of things.

### 1) `build-docs-and-publish`
1. It builds the docs (to use but also to check whether they actually build).
2. It determines the current state of the git ref and sets a `target` variable accordingly.
    1. If running on master, set `target` to master
    2. If running on a release, set `target` to release version
    3. If running due to PR, set `target` to empty string
3. If the `target` is not empty string, it deploys the `html` folder of the built docs to `gh-pages/<target>`. It overwrites anything in `<target>` but ignores any other content in `gh-pages`

### 2) `Update docs versions JSON`
Only runs if the `target` is not empty
1. Clones the `gh-pages` branch and reads out the folders within (ignoring anything starting with `.`)
2. Reads out the folder names, determines which are referring to versions and which not.
3. Finds the maximum version
4. Generates a JSON object encoding the present folders/version and the maximum version
5. Pushes that JSON file to the `gh-pages` (ignoring any other files in the branch).

When you open the docs page, the landing page reads out the versions.json and redirects you to `stable`. If there is no version tagged `stable`, it will redirect to `master`.

### On merging this

Requires a sister PR to be merged first, prepping the `gh-pages` branch: #510 

I’ve purged the gh-pages branch and added docs for the `v1.5.1` release. This way I could a) test the `publish` workflow, b) ensure that there is a stable version present, c) make persistent docs for `v.1.5.1` and d) have a more functional demo.

## Credit

Based on [github.com/brechtm/rinohtype](github.com/brechtm/rinohtype)'s workflow.

### CODE REVIEW

**Comment by till-m** [comment]
@phi-friday I will put your PRs on hold until this is sorted out, because any merge conflict on `gh-pages` would be horrible to resolve. My apologies.

**Comment by phi-friday** [comment]
> @phi-friday I will put your PRs on hold until this is sorted out, because any merge conflict on `gh-pages` would be horrible to resolve. My apologies.

I'm sorry I can't help you with that, I'm not familiar with the documentation. 

I looked at the link you showed as an example and it seems to be better in accessibility,
like dark mode support and clipboard support, so good luck with that. 

PR checks are always welcome.

**Comment by phi-friday** [comment]
The `code_docs` looks like it needs some work.
The variable name and type are not separated by a space.

스크린샷 2024-07-27 오후 12 54 50

**Comment by phi-friday** [comment]
> The `code_docs` looks like it needs some work. The variable name and type are not separated by a space.

When written like ```pbounds: dict```, it looks fine, 
but when written like ```pbounds : dict```, the spaces disappear.

**Comment by till-m** [comment]
Technically adding a space before the colon is the correct version, as specififed in the [numpydoc style guide](https://numpydoc.readthedocs.io/en/latest/format.html#parameters).

**Comment by till-m** [comment]
I raised an issue about this at jbms/sphinx-immaterial#375

**Comment by till-m** [comment]
Fixed by adding an extension! [Link](https://till-m.github.io/BayesianOptimization/master/code_docs.html) (master only)!

I will backport this fix along with any other changes requested to the v1.5.1 commit once this PR is approved. Until then, I'm marking #510 as a draft.

**Comment by till-m** [comment]
Added a warning to the `.maximize` docstring to cover #513.

**Comment by till-m** [comment]
I backported all configuration changes to the `v1.5.1` documentation (e.g. the numpydocs codestyle). From my side, this PR is good to go -- there's nothing I feel the need to change at this stage.

See the demo [here](https://till-m.github.io/BayesianOptimization/).

@fmfn @bwheelz36 I would appreciate if you find a chance to review this. Given that the docs are in a sense the face of this project, I want to make sure no one is unhappy with the outcome.

**Pull request merged**
